[browser]
serverAddress = "localhost"
serverPort = 8501
gatherUsageStats = false

[server]
maxUploadSize = 200
enableXsrfProtection = false
enableCORS = false
headless = true

[runner]
fastReruns = true
enforceSerializableSessionState = false

[theme]
primaryColor = "#1c83e1"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif" 